import mongoose from 'mongoose';
import dotenv from 'dotenv';
import DisplayPreset from '../models/DisplayPreset.js';
import ColorTheme from '../models/ColorTheme.js';
import FooterPreset from '../models/FooterPreset.js';

dotenv.config();

const displayPresets = [
  {
    name: 'Classic',
    description: 'A timeless, professional layout suited for all business cards.',
    category: 'Business',
    status: 'published',
    headerStyle: 'Curved Wave',
    headerHeight: '220px',
    backgroundType: 'Solid Color',
    profilePhotoStyle: 'Circle',
    profilePhotoPosition: 'Overlapping Header',
    cardShape: 'Rounded',
    animationStyle: 'Fade',
    buttonStyle: 'Rounded',
    dividerStyle: 'Subtle',
    sectionSpacing: 'Normal',
    typography: 'Modern Sans',
    badgePosition: 'Top Right',
  },
  {
    name: 'Flat',
    description: 'Clean, modern flat design with no shadows or gradients.',
    category: 'Minimal',
    status: 'published',
    headerStyle: 'Solid Color',
    headerHeight: '180px',
    backgroundType: 'Solid Color',
    profilePhotoStyle: 'Square',
    profilePhotoPosition: 'Left',
    cardShape: 'Sharp',
    animationStyle: 'None',
    buttonStyle: 'Rectangular',
    dividerStyle: 'Solid',
    sectionSpacing: 'Normal',
    typography: 'Modern Sans',
    badgePosition: 'Inline',
  },
  {
    name: 'Modern',
    description: 'Sleek contemporary design with sharp edges and bold typography.',
    category: 'Business',
    status: 'published',
    headerStyle: 'Diagonal Split',
    headerHeight: '240px',
    backgroundType: 'Gradient',
    profilePhotoStyle: 'Rounded Square',
    profilePhotoPosition: 'Floating',
    cardShape: 'Soft Shadow',
    animationStyle: 'Slide',
    buttonStyle: 'Pill',
    dividerStyle: 'None',
    sectionSpacing: 'Spacious',
    typography: 'Display',
    badgePosition: 'Top Right',
  },
  {
    name: 'Sleek',
    description: 'Ultra-minimal design optimised for high-impact personal branding.',
    category: 'Personal',
    status: 'published',
    headerStyle: 'Gradient',
    headerHeight: '260px',
    backgroundType: 'Solid Color',
    profilePhotoStyle: 'Circle',
    profilePhotoPosition: 'Center',
    cardShape: 'Borderless',
    animationStyle: 'Scale',
    buttonStyle: 'Outline',
    dividerStyle: 'Subtle',
    sectionSpacing: 'Spacious',
    typography: 'Elegant Serif',
    badgePosition: 'Hidden',
  },
  {
    name: 'Blend',
    description: 'Smooth colour transitions that blend header into card body.',
    category: 'Personal',
    status: 'published',
    headerStyle: 'Gradient',
    headerHeight: '250px',
    backgroundType: 'Animated Gradient',
    profilePhotoStyle: 'Gradient Border',
    profilePhotoPosition: 'Center',
    cardShape: 'Glass',
    animationStyle: 'Glow',
    buttonStyle: 'Rounded',
    dividerStyle: 'None',
    sectionSpacing: 'Normal',
    typography: 'Modern Sans',
    badgePosition: 'Inline',
  },
  {
    name: 'Creative',
    description: 'Bold, expressive layout for designers, artists and creators.',
    category: 'Creative',
    status: 'published',
    headerStyle: 'Organic Blob',
    headerHeight: '280px',
    backgroundType: 'Solid Color',
    profilePhotoStyle: 'Shadow',
    profilePhotoPosition: 'Floating',
    cardShape: 'Border',
    animationStyle: 'Bounce',
    buttonStyle: 'Pill',
    dividerStyle: 'Dashed',
    sectionSpacing: 'Spacious',
    typography: 'Display',
    badgePosition: 'Top Right',
  },
  {
    name: 'Luxury',
    description: 'Premium dark design with gold accents for elite professionals.',
    category: 'Luxury',
    status: 'published',
    headerStyle: 'Solid Color',
    headerHeight: '200px',
    backgroundType: 'Solid Color',
    profilePhotoStyle: 'Gradient Border',
    profilePhotoPosition: 'Center',
    cardShape: 'Soft Shadow',
    animationStyle: 'Scale',
    buttonStyle: 'Outline',
    dividerStyle: 'Solid',
    sectionSpacing: 'Normal',
    typography: 'Elegant Serif',
    badgePosition: 'Top Right',
  },
  {
    name: 'Aurora',
    description: 'Northern Lights-inspired smooth blended gradient for a premium, elegant feel.',
    category: 'Creative',
    status: 'published',
    headerStyle: 'Aurora',
    headerHeight: '260px',
    backgroundType: 'Solid Color',
    profilePhotoStyle: 'Glass Border',
    profilePhotoPosition: 'Overlapping Header',
    cardShape: 'Rounded',
    animationStyle: 'Fade',
    buttonStyle: 'Rounded',
    dividerStyle: 'Subtle',
    sectionSpacing: 'Normal',
    typography: 'Modern Sans',
    badgePosition: 'Top Right',
  },
  {
    name: 'Minimal',
    description: 'Pure whitespace, no distractions — just your information.',
    category: 'Minimal',
    status: 'published',
    headerStyle: 'Solid Color',
    headerHeight: '160px',
    backgroundType: 'Solid Color',
    profilePhotoStyle: 'No Border',
    profilePhotoPosition: 'Left',
    cardShape: 'Borderless',
    animationStyle: 'None',
    buttonStyle: 'Ghost',
    dividerStyle: 'None',
    sectionSpacing: 'Spacious',
    typography: 'Modern Sans',
    badgePosition: 'Hidden',
  },
  {
    name: 'Executive',
    description: 'Corporate layout, left-aligned header, subtle dividers.',
    category: 'Corporate',
    status: 'published',
    headerStyle: 'Solid Color',
    headerHeight: '180px',
    backgroundType: 'Solid Color',
    profilePhotoStyle: 'Square',
    profilePhotoPosition: 'Left',
    cardShape: 'Rounded',
    animationStyle: 'Fade',
    buttonStyle: 'Rectangular',
    dividerStyle: 'Subtle',
    sectionSpacing: 'Compact',
    typography: 'Modern Sans',
    badgePosition: 'Top Right',
  },
];

const colorThemes = [
  {
    name: 'Ocean Blue',
    category: 'Business',
    status: 'published',
    primary: '#0ea5e9',
    secondary: '#0369a1',
    accent: '#38bdf8',
    background: '#f0f9ff',
    surface: '#ffffff',
    text: '#0c4a6e',
    border: '#bae6fd',
    button: '#0ea5e9',
    icon: '#0369a1',
  },
  {
    name: 'Midnight Dark',
    category: 'Business',
    status: 'published',
    primary: '#818cf8',
    secondary: '#4f46e5',
    accent: '#c7d2fe',
    background: '#0f172a',
    surface: '#1e293b',
    text: '#f1f5f9',
    border: '#334155',
    button: '#818cf8',
    icon: '#a5b4fc',
  },
  {
    name: 'Rose Gold',
    category: 'Luxury',
    status: 'published',
    primary: '#e11d48',
    secondary: '#9f1239',
    accent: '#fb7185',
    background: '#fff1f2',
    surface: '#ffffff',
    text: '#881337',
    border: '#fecdd3',
    button: '#e11d48',
    icon: '#be123c',
  },
  {
    name: 'Forest Green',
    category: 'Personal',
    status: 'published',
    primary: '#16a34a',
    secondary: '#15803d',
    accent: '#4ade80',
    background: '#f0fdf4',
    surface: '#ffffff',
    text: '#14532d',
    border: '#bbf7d0',
    button: '#16a34a',
    icon: '#15803d',
  },
  {
    name: 'Sunset Orange',
    category: 'Creative',
    status: 'published',
    primary: '#ea580c',
    secondary: '#c2410c',
    accent: '#fb923c',
    background: '#fff7ed',
    surface: '#ffffff',
    text: '#7c2d12',
    border: '#fed7aa',
    button: '#ea580c',
    icon: '#c2410c',
  },
  {
    name: 'Monochrome',
    category: 'Minimal',
    status: 'published',
    primary: '#171717',
    secondary: '#404040',
    accent: '#737373',
    background: '#ffffff',
    surface: '#fafafa',
    text: '#171717',
    border: '#e5e5e5',
    button: '#171717',
    icon: '#525252',
  },
  {
    name: 'Violet Dream',
    category: 'Creative',
    status: 'published',
    primary: '#7c3aed',
    secondary: '#6d28d9',
    accent: '#a78bfa',
    background: '#f5f3ff',
    surface: '#ffffff',
    text: '#4c1d95',
    border: '#ddd6fe',
    button: '#7c3aed',
    icon: '#6d28d9',
  },
  {
    name: 'Gold Luxury',
    category: 'Luxury',
    status: 'published',
    primary: '#b45309',
    secondary: '#92400e',
    accent: '#f59e0b',
    background: '#1c1917',
    surface: '#292524',
    text: '#fef3c7',
    border: '#44403c',
    button: '#f59e0b',
    icon: '#d97706',
  },
  {
    name: 'Coral Breeze',
    category: 'Personal',
    status: 'published',
    primary: '#f43f5e',
    secondary: '#e11d48',
    accent: '#fb7185',
    background: '#fff1f2',
    surface: '#ffffff',
    text: '#881337',
    border: '#fecdd3',
    button: '#f43f5e',
    icon: '#e11d48',
  },
  {
    name: 'Steel Corporate',
    category: 'Corporate',
    status: 'published',
    primary: '#1e40af',
    secondary: '#1d4ed8',
    accent: '#60a5fa',
    background: '#f8fafc',
    surface: '#ffffff',
    text: '#1e3a5f',
    border: '#cbd5e1',
    button: '#1e40af',
    icon: '#1d4ed8',
  },
  {
    name: 'Neon Nights',
    category: 'Creative',
    status: 'published',
    primary: '#a855f7',
    secondary: '#ec4899',
    accent: '#22d3ee',
    background: '#09090b',
    surface: '#18181b',
    text: '#fafafa',
    border: '#3f3f46',
    button: '#a855f7',
    icon: '#ec4899',
  },
  {
    name: 'Sage Minimal',
    category: 'Minimal',
    status: 'published',
    primary: '#4d7c5f',
    secondary: '#3f6b50',
    accent: '#86efac',
    background: '#f7faf8',
    surface: '#ffffff',
    text: '#1a3a25',
    border: '#d1fae5',
    button: '#4d7c5f',
    icon: '#3f6b50',
  },
];

const footerPresets = [
  {
    name: 'Powered by Identiqal',
    status: 'published',
    isPremium: false,
    contentTemplate: 'Powered by Identiqal',
  },
  {
    name: 'Create Your Card',
    status: 'published',
    isPremium: false,
    contentTemplate: 'Create your own card at Identiqal',
  },
  {
    name: 'No Footer',
    status: 'published',
    isPremium: false,
    contentTemplate: '',
  },
  {
    name: 'QR Code Footer',
    status: 'published',
    isPremium: true,
    contentTemplate: 'Scan to connect',
  },
  {
    name: 'Custom Branding',
    status: 'published',
    isPremium: true,
    contentTemplate: '{{custom}}',
  },
  {
    name: 'Social Links Bar',
    status: 'published',
    isPremium: true,
    contentTemplate: 'Follow me on social media',
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ Connected to MongoDB');

    // Clear existing
    await DisplayPreset.deleteMany({});
    await ColorTheme.deleteMany({});
    await FooterPreset.deleteMany({});
    console.log('🗑️  Cleared existing presets');

    // Insert fresh
    await DisplayPreset.insertMany(displayPresets);
    console.log(`✅ Inserted ${displayPresets.length} Display Presets`);

    await ColorTheme.insertMany(colorThemes);
    console.log(`✅ Inserted ${colorThemes.length} Color Themes`);

    await FooterPreset.insertMany(footerPresets);
    console.log(`✅ Inserted ${footerPresets.length} Footer Presets`);

    console.log('\n🎉 Seeding complete!');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seeding failed:', err);
    process.exit(1);
  }
}

seed();
